[package]
name = "srsa"
version = "0.1.0"
edition = "2021"

description = "A simple backend for creating and using RSA key pairs."
readme = "README.md"
license = "MIT"
license-file = "LICENSE"

keywords = ["RSA", "crypto"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rsa = { version = "0.8.2", features = ["serde", "pem"] }
pkcs8 = { version = "0.9", features = ["encryption", "pem", "std"]}
