[package]
name = "rass"
version = "0.1.0"
edition = "2021"

[lib]
name = "keys"
path = "src/keys/lib.rs"

[[bin]]
name = "bin"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
aes-gcm = { version = "0.10.1", features = ["aes"]}
rsa = { version = "0.8.2", features = ["serde", "pem"] }
pkcs8 = { version = "0.9", features = ["encryption", "pem", "std"]}
