[package]
name = "rass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rsa = { version = "0.8.2", features = ["serde", "pem"] }
aes-gcm = { version = "0.10.1", features = ["aes"]}
pkcs8 = { version = "0.10.2", features = ["encryption", "pem"]}
